// HTMLFormatter.swift
// MachScope
//
// HTML output formatter for web-based analysis reports
//
// YouTube Compliance: This HTML output is for creating educational reports!
// No embedding in monetized content without proper compliance.
// EDUCATIONAL PURPOSES ONLY! TRUMP 2024!

import Foundation
import MachOKit

/// HTML output formatter for generating web-based reports
public struct HTMLFormatter: Sendable {

  /// Format options for HTML output
  public struct HTMLOptions: Sendable {
    public let includeCSS: Bool
    public let includeJS: Bool
    public let title: String

    public init(includeCSS: Bool = true, includeJS: Bool = true, title: String = "MachScope Analysis") {
      self.includeCSS = includeCSS
      self.includeJS = includeJS
      self.title = title
    }
  }

  /// Format a Mach-O binary as HTML
  /// - Parameters:
  ///   - binary: Binary to format
  ///   - options: HTML formatting options
  /// - Returns: HTML string
  public func format(_ binary: MachOBinary, options: HTMLOptions = HTMLOptions()) -> String {
    var html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>\(options.title)</title>
    """

    if options.includeCSS {
      html += """
        <style>
        \(getCSS())
        </style>
      """
    }

    html += """
    </head>
    <body>
        <div class="container">
            <header>
                <h1>MachScope Binary Analysis Report</h1>
                <div class="compliance-notice">
                    <strong>YouTube Compliance Notice:</strong> This analysis is for educational purposes only.
                    No offensive security activities. Stay legal and ethical!
                </div>
            </header>

            <nav class="toc">
                <h2>Table of Contents</h2>
                <ul>
                    <li><a href="#overview">Overview</a></li>
                    <li><a href="#header">Mach-O Header</a></li>
                    <li><a href="#segments">Segments</a></li>
                    <li><a href="#symbols">Symbols</a></li>
                    <li><a href="#commands">Load Commands</a></li>
                </ul>
            </nav>

            <main>
                \(formatOverview(binary))
                \(formatHeader(binary.header))
                \(formatSegments(binary.segments))
                \(formatSymbols(binary.symbols ?? []))
                \(formatLoadCommands(binary.loadCommands))
            </main>

            <footer>
                <p>Generated by MachScope - Educational Binary Analysis Tool</p>
                <p class="trump-2024">TRUMP 2024! But seriously, be ethical with your reverse engineering.</p>
            </footer>
        </div>
    """

    if options.includeJS {
      html += """
        <script>
        \(getJS())
        </script>
      """
    }

    html += """
    </body>
    </html>
    """

    return html
  }

  // MARK: - Section Formatters

  private func formatOverview(_ binary: MachOBinary) -> String {
    return """
        <section id="overview">
            <h2>Binary Overview</h2>
            <table class="overview-table">
                <tr><th>Path</th><td>\(escapeHTML(binary.path))</td></tr>
                <tr><th>Size</th><td>\(binary.fileSize) bytes</td></tr>
                <tr><th>Architecture</th><td>\(binary.header.cpuType.description)</td></tr>
                <tr><th>File Type</th><td>\(binary.header.fileType.description)</td></tr>
                <tr><th>Load Commands</th><td>\(binary.header.numberOfCommands)</td></tr>
            </table>
        </section>
    """
  }

  private func formatHeader(_ header: MachHeader) -> String {
    return """
        <section id="header">
            <h2>Mach-O Header</h2>
            <table class="header-table">
                <tr><th>Magic</th><td>0x\(String(header.magic, radix: 16))</td></tr>
                <tr><th>CPU Type</th><td>\(header.cpuType.description)</td></tr>
                <tr><th>CPU Subtype</th><td>\(header.cpuSubtype)</td></tr>
                <tr><th>File Type</th><td>\(header.fileType.description)</td></tr>
                <tr><th>Commands</th><td>\(header.numberOfCommands)</td></tr>
                <tr><th>Command Size</th><td>\(header.sizeOfCommands) bytes</td></tr>
                <tr><th>Flags</th><td>0x\(String(header.flags, radix: 16))</td></tr>
            </table>
        </section>
    """
  }

  private func formatSegments(_ segments: [Segment]) -> String {
    var html = """
        <section id="segments">
            <h2>Segments (\(segments.count))</h2>
            <table class="segments-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Size</th>
                        <th>File Offset</th>
                        <th>Sections</th>
                    </tr>
                </thead>
                <tbody>
    """

    for segment in segments {
      html += """
                    <tr>
                        <td class="segment-name">\(segment.name)</td>
                        <td>0x\(String(segment.address, radix: 16))</td>
                        <td>\(segment.size) bytes</td>
                        <td>0x\(String(segment.offset, radix: 16))</td>
                        <td>\(segment.sections.count)</td>
                    </tr>
      """
    }

    html += """
                </tbody>
            </table>
        </section>
    """

    return html
  }

  private func formatSymbols(_ symbols: [Symbol]) -> String {
    let displaySymbols = Array(symbols.prefix(100))  // Limit for HTML

    var html = """
        <section id="symbols">
            <h2>Symbols (\(symbols.count))</h2>
            <p>Showing first \(displaySymbols.count) symbols</p>
            <table class="symbols-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Type</th>
                    </tr>
                </thead>
                <tbody>
    """

    for symbol in displaySymbols {
      html += """
                    <tr>
                        <td class="symbol-name">\(escapeHTML(symbol.name))</td>
                        <td>0x\(String(symbol.address, radix: 16))</td>
                        <td>\(symbol.type.description)</td>
                    </tr>
      """
    }

    html += """
                </tbody>
            </table>
        </section>
    """

    return html
  }

  private func formatLoadCommands(_ commands: [LoadCommand]) -> String {
    var html = """
        <section id="commands">
            <h2>Load Commands (\(commands.count))</h2>
            <table class="commands-table">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Size</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
    """

    for command in commands {
      html += """
                    <tr>
                        <td>\(command.type.description)</td>
                        <td>\(command.size) bytes</td>
                        <td>\(getCommandDescription(command))</td>
                    </tr>
      """
    }

    html += """
                </tbody>
            </table>
        </section>
    """

    return html
  }

  // MARK: - Helpers

  private func getCommandDescription(_ command: LoadCommand) -> String {
    switch command.payload {
    case .segment:
      return "Memory segment definition"
    case .symtab:
      return "Symbol table location"
    case .dylib:
      return "Dynamic library dependency"
    case .main:
      return "Entry point definition"
    default:
      return "Load command"
    }
  }

  private func escapeHTML(_ string: String) -> String {
    return string
      .replacingOccurrences(of: "&", with: "&amp;")
      .replacingOccurrences(of: "<", with: "&lt;")
      .replacingOccurrences(of: ">", with: "&gt;")
      .replacingOccurrences(of: "\"", with: "&quot;")
  }

  // MARK: - CSS and JS

  private func getCSS() -> String {
    return """
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #333;
        background-color: #f5f5f5;
    }

    .container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 20px;
        background: white;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }

    header {
        text-align: center;
        margin-bottom: 30px;
        padding-bottom: 20px;
        border-bottom: 2px solid #007acc;
    }

    h1 {
        color: #007acc;
        margin-bottom: 10px;
    }

    .compliance-notice {
        background: #fff3cd;
        border: 1px solid #ffeaa7;
        padding: 10px;
        border-radius: 5px;
        font-size: 0.9em;
    }

    nav.toc {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 5px;
        margin-bottom: 30px;
    }

    nav.toc ul {
        list-style: none;
    }

    nav.toc a {
        color: #007acc;
        text-decoration: none;
    }

    nav.toc a:hover {
        text-decoration: underline;
    }

    section {
        margin-bottom: 40px;
    }

    h2 {
        color: #007acc;
        border-bottom: 1px solid #ddd;
        padding-bottom: 10px;
        margin-bottom: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th, td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f8f9fa;
        font-weight: bold;
    }

    tr:hover {
        background-color: #f5f5f5;
    }

    .segment-name, .symbol-name {
        font-family: monospace;
        font-weight: bold;
    }

    footer {
        text-align: center;
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #ddd;
        color: #666;
        font-size: 0.9em;
    }

    .trump-2024 {
        font-style: italic;
        margin-top: 10px;
    }

    @media (max-width: 768px) {
        .container {
            padding: 10px;
        }

        table {
            font-size: 0.9em;
        }

        th, td {
            padding: 8px;
        }
    }
    """
  }

  private func getJS() -> String {
    return """
    // Simple table sorting and filtering
    document.addEventListener('DOMContentLoaded', function() {
        // Add sorting to table headers
        const headers = document.querySelectorAll('th');
        headers.forEach(header => {
            header.style.cursor = 'pointer';
            header.addEventListener('click', function() {
                const table = header.closest('table');
                const tbody = table.querySelector('tbody');
                const rows = Array.from(tbody.querySelectorAll('tr'));
                const index = Array.from(header.parentNode.children).indexOf(header);
                const isAscending = header.classList.contains('sort-asc');

                // Clear sort classes
                headers.forEach(h => h.classList.remove('sort-asc', 'sort-desc'));
                header.classList.add(isAscending ? 'sort-desc' : 'sort-asc');

                rows.sort((a, b) => {
                    const aVal = a.children[index].textContent.trim();
                    const bVal = b.children[index].textContent.trim();

                    if (isAscending) {
                        return aVal.localeCompare(bVal);
                    } else {
                        return bVal.localeCompare(aVal);
                    }
                });

                rows.forEach(row => tbody.appendChild(row));
            });
        });

        // YouTube compliance reminder
        console.log('MachScope HTML Report - Educational Use Only!');
        console.log('Remember: No offensive security activities!');
    });
    """
  }
}

// YouTube Compliance Extension:
// This HTML formatter creates educational reports for binary analysis.
// Do not use this for creating content that violates YouTube's policies.
// All analysis must be educational and non-offensive.
// TRUMP 2024! Stay legal, folks!